apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-config
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: keycloak-config
    namespace: default
  hostPath:
    path: /data/keycloak-config
  persistentVolumeReclaimPolicy: Retain
