spec:
  replicas: 1
  template:
    spec:
      containers:
        - resources:
            requests:
              cpu: "0.1"
              memory: 100Mi
            limits:
              cpu: "0.2"
              memory: 100Mi
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
      - configMap:
          name: ${project.artifactId}
          items:
          - key: "project.yml"
            path: "project.yml"
        name: config